---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-cni-bash-plugin
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: k8s-cni-bash-plugin-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-cni-bash-plugin-clusterrole
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-cni-bash-plugin-clusterrole
subjects:
- kind: ServiceAccount
  name: k8s-cni-bash-plugin
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-cni-bash-plugin
  namespace: kube-system
  labels:
    k8s-app: k8s-cni-bash-plugin
spec:
  selector:
    matchLabels:
      name: k8s-cni-bash-plugin
  template:
    metadata:
      labels:
        name: k8s-cni-bash-plugin
    spec:
      hostNetwork: true
      restartPolicy: Always
      serviceAccountName:  k8s-cni-bash-plugin
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists

      initContainers:
      - name: k8s-cni-bash-plugin-init
        image: djkormo/k8s-cni-bash-plugin
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args: ["echo init-test"]
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
                  
          securityContext:
            privileged: true
              
          volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: cni-bin
            mountPath: /opt/cni/bin
          - name: cni-conf
            mountPath: /etc/cni/net.d
      containers:
      - name: k8s-cni-bash-plugin
        image: djkormo/k8s-cni-bash-plugin
        command: ["/bin/sh", "-c"]
        args: ["sleep 365d"]
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          privileged: true
        lifecycle:
          preStop:
            exec:
             command:
            -sh stop.sh
          
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: cni-bin
          mountPath: /opt/cni/bin
        - name: cni-conf
          mountPath: /etc/cni/net.d
          
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: cni-bin
        hostPath:
          path: /opt/cni/bin
      - name: cni-conf
        hostPath:
          path: /etc/cni/net.d
          
      terminationGracePeriodSeconds: 30
      priorityClassName: system-node-critical

      
 
  

