apiVersion: v1
kind: Pod
metadata:
  name: tool-pod
  namespace: default
spec:
  containers:
  - args:
    - sleep
    - "360000"
    image: busybox:latest
    name: busybox
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Never
