apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-cni-bash-plugin-configmap
  namespace: kube-system
data:
  10-k8s-cni-bash-plugin.conf: |
    {
        "cniVersion": "0.3.1",
        "name": "k8s-cni-bash-plugin",
        "type": "k8s-cni-bash-plugin",
        "bridge": "cni0",
        "hostnetwork: "10.244.0.0/16",
        "podnetwork": "10.240.0.0/16",
        "podcidr": "10.240.node_number.0/24"
    }

