---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-cni-bash-plugin
  namespace: kube-system
  labels:
    k8s-app: k8s-cni-bash-plugin
spec:
  selector:
    matchLabels:
      name: k8s-cni-bash-plugin
  template:
    metadata:
      labels:
        name: k8s-cni-bash-plugin
    spec:
      hostNetwork: true
      restartPolicy: Always
      serviceAccountName:  k8s-cni-bash-plugin
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists

      initContainers:
      - name: k8s-cni-bash-plugin-init
        image: djkormo/k8s-cni-bash-plugin:main
        imagePullPolicy: Always
        command: ["/cni/start.sh"]
        env:
        - name: CNI_PODNETWORK  # IP of APP pods
          value: "10.240.0.0/16"
        - name: CNI_NODEMASK  # CIDR mask for single node 10.240.0.0/24, 10.240.1.0/24, 10.240.2.0/24, ...
          value: "24" 
        - name: CNI_LOGFILE
          value: /var/log/cni.log
        - name: CNI_HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CNI_PODNAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace   
        - name: CNI_PODIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
                  
        securityContext:
          privileged: true
              
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: cni-bin
          mountPath: /opt/cni/bin
        - name: cni-conf
          mountPath: /etc/cni/net.d
        - name: cni-tmp
          mountPath: /tmp

      containers:
      - name: k8s-cni-bash-plugin
        image: djkormo/k8s-cni-bash-plugin
        command: ["/bin/sh", "-c"]
        args: ["sleep 365d"]
        env:
        - name: CNI_PODNETWORK  # IP of APP pods
          value: "10.240.0.0/16"
        - name: CNI_NODEMASK  # CIDR mask for single node 10.240.0.0/24, 10.240.1.0/24, 10.240.2.0/24, ...
          value: "24" 
        - name: CNI_LOGFILE
          value: /var/log/cni.log
        - name: CNI_HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CNI_PODNAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CNI_PODIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          privileged: true

        lifecycle:

          preStop:
            exec:
              command: [
                # shutdown cni
                "/cni/stop.sh"
              ]
          
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: cni-bin
          mountPath: /opt/cni/bin
        - name: cni-conf
          mountPath: /etc/cni/net.d
        - name: cni-tmp
          mountPath: /tmp
        - name: cni-ipam
          mountPath: /var/lib/cni/networks/k8s-cni-bash-plugin
          
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: cni-ipam
        hostPath:
          path: /var/lib/cni/networks/k8s-cni-bash-plugin
      - name: cni-bin
        hostPath:
          path: /opt/cni/bin
      - name: cni-conf
        hostPath:
          path: /etc/cni/net.d
      - name: cni-tmp
        hostPath:
          path: /tmp/k8s-cni-bash-plugin
          type: DirectoryOrCreate
          
      terminationGracePeriodSeconds: 30
      priorityClassName: system-node-critical

      
 
  

