from curlimages/curl:8.2.1
COPY k8s-api-check.bash k8s-api-check.bash
COPY 10-k8s-cni-bash-plugin.conf 10-k8s-cni-bash-plugin.conf
COPY k8s-cni-bash-plugin.bash k8s-cni-bash-plugin.bash
COPY init.sh init.sh



